.TH ESH 1 
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
esh \- the easy shell
.SH SYNOPSIS
.B esh
.SH "DESCRIPTION"
This manual page documents briefly the
.BR esh
commands.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
Instead, it has documentation in the GNU Info format; see below.
.PP
.B esh
was primarily written out of a need for a simple and lightweight shell
for Unix. As such, it deviates completely from all of the traditional
shells, opting instead for a Lisp-like syntax. This allows exceptionally 
small size, both in terms of lines of code and memory consumption, while
retaining remarkable flexibility and programmability.
.SH OPTIONS
To start the shell, simply type 
.B esh
. There are no command-line 
parameters. However, since all the command-line arguments are available
to the shell programmer, it is a simple matter to write your own argument
processing routine and place it in your 
.B \.eshrc
file.
.SH "SEE ALSO"
The programs are documented fully by
.IR "esh, the easy shell" ,
available via the doc-base and Info system.
.SH AUTHOR
This manual page was written by Edward Betts <edward@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
